#include "io.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

#include "pdfgen.h"

unsigned char* load_image_file(const char* path, int* w, int* h, int* c) {
    // Force 3 channels (RGB) for simplicity
    return stbi_load(path, w, h, c, 3);
}

// Helper: Extract sub-image buffer
// Returns a new buffer that must be freed.
static unsigned char* crop_image(const unsigned char* src, int w, int h, int c, int y_start, int y_end, int* out_h) {
    int crop_h = y_end - y_start;
    *out_h = crop_h;
    if (crop_h <= 0) return NULL;

    unsigned char* dest = (unsigned char*)malloc(w * crop_h * c);
    if (!dest) return NULL;

    // Copy row by row or block copy
    // src layout: row major.
    // Start offset: y_start * w * c
    // Size: crop_h * w * c
    size_t offset = (size_t)y_start * w * c;
    size_t size = (size_t)crop_h * w * c;
    memcpy(dest, src + offset, size);
    
    return dest;
}

bool save_pdf(const char* output_path, const unsigned char* image_data, int width, int height,
              const CutList* cuts, int target_height_px, RenderMode mode, int dpi) {
    
    struct pdf_info info = {
        .creator = "Content Aware Pagination C",
        .producer = "CAP-C",
        .title = "Paginated Document",
        .author = "User",
        .subject = "Generated by CAP-C"
        // date will be auto-filled or left empty
    };

    // Calculate page size in points
    // Width points = width_px * 72 / dpi
    float page_width_pt = (float)width * 72.0f / dpi;
    // Default height for initial layout, but we change it per page?
    // PDFGen uses a strict page size per doc structure or per page?
    // pdfgen API: pdf_create(width, height, info).
    // But pdf_append_page allows passing width/height? 
    // Checking pdfgen.h (assumed API): 
    // wrapper: pdf_create(width, height, info)
    // pdf_append_page(pdf) -> uses default?
    // Actually, AndreRenaud/PDFGen allows setting page size if we use specific calls or if it supports variable page sizes.
    // Assuming variable page size might not be fully supported by basic `pdf_create`, but let's check standard usage.
    // If not, we set the max height or target height.
    // Let's use target_height_px converted to points as the default.
    
    float default_height_pt = (float)target_height_px * 72.0f / dpi;

    struct pdf_doc *pdf = pdf_create(page_width_pt, default_height_pt, &info);
    if (!pdf) {
        fprintf(stderr, "Failed to create PDF context.\n");
        return false;
    }

    // Loop cuts
    for (int i = 0; i < cuts->count - 1; ++i) {
        int start = cuts->cuts[i];
        int end = cuts->cuts[i+1];
        
        int crop_h = 0;
        unsigned char* crop_buf = crop_image(image_data, width, height, 3, start, end, &crop_h);
        if (!crop_buf) continue;

        float crop_height_pt = (float)crop_h * 72.0f / dpi;
        
        // If render mode is variable size, we might want the page to match the crop
        // PDFGen might default to the doc size.
        // There is 'pdf_set_page_height' or similar?
        // If strict PDFGen doesn't allow changing page size easily mid-doc, we might have scaling artifacts or whitespace.
        // But for "variable_size" logic, usually PDF pages can be different sizes.
        // Let's assume pdfgen uses the document size for all pages unless overriden.
        // Override isn't clearly standard in the simplest API. 
        // We will stick to adding a page.
        
        pdf_append_page(pdf); // Adds page with default size?

        // Ideally we want: pdf_add_image_data(pdf, page, data, x, y, w, h)
        // Adjust PDF page height?
        // If not possible, we just center or top-align.
        // Let's rely on standard behavior: Page size is fixed to whatever was passed in pdf_create.
        // If we want variable, we might need to be clever.
        // Retaining simple logic: Create page of target height.
        // If crop is larger/smaller, we draw it?
        
        // Actually, pdfgen `pdf_add_image_data` does not take a page argument usually, it adds to "current" page.
        // Function signature: pdf_add_rgb(pdf, NULL, x, y, display_w, display_h, data, data_w, data_h)
        // If wrapper is used.
        // Let's try: pdf_add_image_data(pdf, NULL, x, y, w, h, data, w, h)
        // Wait, pdfgen.h often has `pdf_add_image` or `pdf_add_rgb`.
        // I will guess standard wrapper: `pdf_add_rgb`
        
        // Coordinates: PDF is bottom-left origin usually.
        // But pdfgen might abstract this to top-left?
        // AndreRenaud/PDFGen usually uses bottom-left.
        // So to draw at top, we need y = page_height - image_height.
        
        float draw_y = default_height_pt - crop_height_pt;
        if (draw_y < 0) draw_y = 0; // Crop bigger than page?
        
        pdf_add_rgb(pdf, NULL, 0, draw_y, page_width_pt, crop_height_pt, crop_buf, width, crop_h);

        free(crop_buf);
    }

    pdf_save(pdf, output_path);
    pdf_destroy(pdf);
    return true;
}
